### ISSUE TITLE
Iframe - Reload login

### ISSUE THREAD

**Issue by bcastane** [Tychobra/polished#115]
Hi,
I embeded my shinnyapps.io into an iframe using polished to login. The issue here is that when I succesesfully login the iframe reload and appears the the sign in form again. If I do it sign in directly in the app from shinnyapps.io it works. 

How can i make it work from an iframe (or similar)?

Thanks

**Comment by merlinoa** [comment]
Thanks for this issue, and thanks for your patience while we worked on a fix.  If you install the latest dev version of polished with 

```
remotes::install_github("tychobra/polished")
```

polished authentication should now work through an iframe on most browsers.  However, it will not work on Safari.  In general, browsers are getting stricter about cookies in iframes.  Eventually browsers will likely block cookie based authentication through iframes, and when they do, this work around will no longer work.  But for now, you should be good to go, for most browsers (including Chrome).

**Comment by bcastane** [comment]
Great, currently i am using it in Chrome so now works great.
Thanks!
