### ISSUE TITLE
cannot get past verification emial sent page

### ISSUE THREAD

**Issue by mauritzvdworm** [Tychobra/polished#124]
Hi there,

I am playing around with your authentication for shiny apps which will be super helpful for me.

Starting with the minimal example, after logging in, I cannot get past the verification email sent page.

![image](https://user-images.githubusercontent.com/12235418/101753636-8d6e5880-3adb-11eb-9b87-0c966c279c6e.png)

The secure content is also not displayed.

Currently using R version 4.0.2 and polished_0.2.0

Any ideas how to get past this?

**Comment by mauritzvdworm** [comment]
Found a quick fix,

`
global_sessions_config(
  app_name = "my-app,
  api_key = "my-app-api-key",
  is_email_verification_required = FALSE
)
`

Added the last line above and now it works.

**Comment by merlinoa** [comment]
I just checked our email logs, and it looks like your email provider is rejecting our verification emails.  We try to make it look like the verification email comes from your email address, but some email providers don't like this.  If you want to enable email verification, can you try changing the "From" value on the "Email Templates" page to "noreply@tychobra.com"?  Let me know if you still are not receiving verification emails after this change.

**Comment by merlinoa** [comment]
We've updated the email templates to now only send emails from noreply@polished.tech.  This is a little unfortunate because we cannot allow users to make it appear that emails are coming directly from their email address, but it resolves this issue where certain email servers were rejecting emails as spam.
