### ISSUE TITLE
Release polished 0.2.1

### ISSUE THREAD

**Issue by jimbrig** [Tychobra/polished#131]
Prepare for release:

* [ ] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_polished.html)
* [ ] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [ ] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [ ] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`

Submit to CRAN:

* [ ] `usethis::use_version('patch')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`

**Comment by jimbrig** [comment]
@merlinoa see https://github.com/Tychobra/polished/releases/edit/untagged-1f1582126b206f048f4d

**Comment by merlinoa** [comment]
@jimbrig we aren't doing this release yet
