### ISSUE TITLE
Secure function for flexdashboard - runtime: shiny?

### ISSUE THREAD

**Issue by mjfrigaard** [Tychobra/polished#137]
Does the `polished` package have a `polished::secure_` variant to pass a `flexdashboard` with the YAML header set to `runtime: shiny`?

I have a rather long-winded explanation of the issue I ran into [here](https://github.com/mjfrigaard/dataset-viewer/blob/main/vignettes/pw-protection.md)

I've been trying to get the authentication to work on [this `flexdashboard` shiny application](https://mjfrigaard.shinyapps.io/csviewer-dashboard/). The example from [your repo](https://github.com/Tychobra/polished_example_apps) has a [broken url](https://tychobra.shinyapps.io/05_flex_dashboard), but I noticed the `polished::secure_static()` function is looking for an .html file--can this take a url for the application on the shiny server?

**Comment by merlinoa** [comment]
I have updated the links in the examples repo README.  Thanks for pointing that out!  This is the correct link to the Rmd example: https://demo5.polished.tech/

And that is a great explanation in your link!  Unfortunately polished does not work with Rmd documents with runtime: shiny.   It only works for regular/static html documents created from .Rmd.  Here is a similar GitHub issue: https://github.com/Tychobra/polished_example_apps/issues/17

I'll keep this issue open until we support .Rmds with runtime: shiny, but it will probably be a while.  Sorry for the inconvenience.

**Comment by mjfrigaard** [comment]
Thank you for getting back to me so quickly! I'm somewhat relieved to hear it wasn't user error on my part :) I will close this issue since it appears you have a similar one open. 

Cheers!
