### ISSUE TITLE
Polished.tech Dashboard

### ISSUE THREAD

**Issue by Lwan12** [Tychobra/polished#139]
Hi,

Polished is an amazing R package and is very helpful to me. 

And I am very interested in [Polished dashborad](https://dashboard.polished.tech/?) program, there is a function I don’t know how to implement it with RShiny.

The function is how you present two interfaces in one menuItem(just like menuitem='shiny apps'), and the second interface is presented according to the different APP name selected in the first interface.

Does this dashboard have open source code? Or how this part is realized, can you give me some hints, thank you！
![polish](https://user-images.githubusercontent.com/58202282/117644297-eb52b980-b1bb-11eb-9a0c-203b386bac38.gif)

**Comment by merlinoa** [comment]
For this particular functionality, we just use the shinyjs R package and show/hide the content when the user click to edit an app.  We detect the button clicks by adding Javascript event listeners and sending info about the app being edited back to Shiny.  These apps follow a similar pattern of using a small amount of custom Javascript with Shiny: https://github.com/Tychobra/shiny_crud

I'm going to close this out as it is not really relevant to polished
