### ISSUE TITLE
User self-delete from polished.tech dashboard

### ISSUE THREAD

**Issue by nathhenry3** [Tychobra/polished#142]
Hello, 

Is there a way for users to delete their own account? At the moment I can't find any way in the polished documentation, so have to do it manually, AND figure out a way for the user to alert me that they want their account deleted. Seems that this will be an issue for GDPR compliance etc - users should have the right to delete their own account details etc.

Thanks for the work you're doing - this package is great!

**Comment by phoward38** [comment]
Hey @nathhenry3 

Are you referring to deleting your own account, or removing one of your users from your account at their request? If you're asking about the latter, can you provide the use case you had in mind for this?

**Comment by nathhenry3** [comment]
Hi Patrick,

At this stage I'm planning to use my app for research purposes. For this, I need to provide users with the option to delete their own account. At the moment, I have to wait for the user to manually alert me (via email, or via some alert button that I create in the app) that they want to delete the account, at which point I have to go into the system and manually delete the account for them (both to remove their data from the system AND to ensure that I don't get charged more for an unnecessary user on polished.tech).

Even if the app wasn't used for research purposes, it seems that this would be a useful feature to any polished users who want this process automated, rather than having to manually delete any users that are no longer using the app?

**Comment by merlinoa** [comment]
Yep 100% agree.  I'm working on the API wrappers to enable this now.  They will be ready within a week.  I'll update this issue when they are live.

**Comment by phoward38** [comment]
Hi @nathhenry3, the newest CRAN release includes API wrapper functions (Example: `polished::delete_user`) that resolve this issue. You can find more documentation about these functions [here](https://polished.tech/docs/3-01-auth-api)

**Comment by nathhenry3** [comment]
That's great news, thank you very much!
