### ISSUE TITLE
Installation error - object 'hideFeedback' is not exported by 'namespace:shinyFeedback'

### ISSUE THREAD

**Issue by nathhenry3** [Tychobra/polished#145]
Hi again...

I've now got an issue with installing the latest dev version of polished from Dockerfile...I get the following error message:

```
Error: object ‘hideFeedback’ is not exported by 'namespace:shinyFeedback'
Execution halted
ERROR: lazy loading failed for package ‘polished’
```

A check of the logfile shows that shinyFeedback installed correctly earlier in the chain. I've never had any issues with it before.

Could this have been caused by any of the latest updates pertaining to polishedpayments?

Thanks again

**Comment by merlinoa** [comment]
Not sure.  That is strange.  Can you make sure you have the latest CRAN release of shinyFeedback (version 0.3.0)? If not can you install it with  `install.packages("shinyFeedback")` and try and install polished again wtih `remotes::install_packages("tychobra/polished")`?

**Comment by nathhenry3** [comment]
Reinstalling those versions seems to work fine on my development environment, but when I switch to Dockerfile it's having issues. I've just tried adding an explicit install of v0.3.0 to the Dockerfile, probably won't change anything but I will know in 2 hours.

**Comment by nathhenry3** [comment]
It's working! Not entirely sure why as I could see that shinyFeedback was installed earlier in the log file, but explicitly installing it seems to be a good workaround. The app appears to be fully functional now. Thank you!
