### ISSUE TITLE
Not being able to add an app user

### ISSUE THREAD

**Issue by farhadsalimi** [Tychobra/polished#147]
Hi,
I'm not sure whether here is the best place to ask.
I am having issues with adding app users in the Polished dashboard, it gives me the error below.
<img width="413" alt="Screen Shot 2021-09-01 at 12 13 32 am" src="https://user-images.githubusercontent.com/17774002/131518865-1ea559a2-a278-421d-81f5-c240a4be2fea.png">

**Comment by merlinoa** [comment]
This should be fixed now.  Sorry, I'm in the middle of rolling out some updates and introduced this bug.  We should be done with the updates by end of day tomorrow.
