### ISSUE TITLE
Using the user email address

### ISSUE THREAD

**Issue by farhadsalimi** [Tychobra/polished#149]
Is there a way to extract the user's email address as a character to use it later on (e.g as a title of a plot)?

**Comment by farhadsalimi** [comment]
Just to clarify further, I would like to know how this can be done using polished:
https://shiny.rstudio.com/articles/permissions.html

**Comment by farhadsalimi** [comment]
I managed to figure it out :)
"session$userData$user()[3]" in the server will give use the email address

**Comment by merlinoa** [comment]
Yep, that's it.  You can access is more explicitly with `session$userData$user()$email`
