### ISSUE TITLE
Sentry option

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polished#150]
https://github.com/Tychobra/polished/blob/8d92f9cc21875f6c5636dc60960065f9cb5af5a8/R/secure_ui.R#L124

Shouldn't this be `sentry_dsn <- getOption("polished")$sentry_dsn` instead?

**Comment by merlinoa** [comment]
Yes updated thanks.  I think it actually worked with just "sentry" due to R's partial matching, but certainly better to use the correct option name.
