### ISSUE TITLE
Polished Hosting - support golem app

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished#152]

**Comment by richardsprague** [comment]
Thanks for looking into this.  FWIW, my workaround fails too, where I try a super-simple `app.r` that simply loads and calls a golem-based package.  https://github.com/personalscience/diycgm/tree/golem

**Comment by phoward38** [comment]
Hi @richardsprague,

Polished Hosting now supports deploying apps as a `golem` package. The `polished::deploy_app()` function has a new argument `golem_package_name`, where you provide the name of your `golem` package (app) as a character string. The example `golem` application I used to test deploying to hosting is provided [here](https://github.com/Tychobra/polished_example_apps/tree/master/08_polishedGolemApp) in our [polished_example_apps](https://github.com/Tychobra/polished_example_apps) repo.

Feel free to reopen this issue if you have any questions or issues while trying to deploy your golem app, and thanks for using `polished`!
