### ISSUE TITLE
Can't unset to NULL

### ISSUE THREAD

**Issue by muschellij2** [Tychobra/polished#167]
The reason I had set this to NA in the past is that you can't `unset` to `NULL`, it'll give you an error.
https://github.com/Tychobra/polished/blob/c070245c6ea52f44e9a87905eabf0fec05efa82f/R/api_00.R#L96

**Comment by muschellij2** [comment]
``` r
Sys.getenv("anything", unset = NULL)
#> Error in Sys.getenv("anything", unset = NULL): wrong type for argument
```

**Comment by merlinoa** [comment]
Yep I just noticed that as well.  My bad.  Thanks
