### ISSUE TITLE
Error message does not match argument

### ISSUE THREAD

**Issue by mrbsoftisms** [Tychobra/polished#187]
In `deploy_app` the RAM value stop message says `ram_db` should be `ram_gb`.  

```
  if (!(ram_gb %in% c(2, 4, 8, 16))) {
    stop("`ram_db` must be 2, 4, 8, or 16", call. = FALSE)
  }

```

**Comment by phoward38** [comment]
@mrbsoftisms Thanks for pointing that out! Resolved the issue with 1740f5e75c82e3dcaa4ff6b4916a093459780f4d
