### ISSUE TITLE
Polished Hosting: Cannot deploy golem app

### ISSUE THREAD

**Issue by aeynaud** [Tychobra/polished#192]
Hi, I have attempted for the first time to deploy my golem app to polished. 
I have used the golem_package_name argument of the deploy_app() function but I received the following warning after about 10 minutes: 

![image](https://user-images.githubusercontent.com/52440398/176929711-3214796e-ab74-4583-abae-17d37deff708.png)

Could you please help me figure it out? Is there anyone I can contact from polished?
Thank you in advance.

**Comment by merlinoa** [comment]
I just tested deploying this Golem app: https://github.com/Tychobra/polished_example_apps/tree/master/08_golem_app

And the app deployed successfully.  Are you able to build the package containing your Golem app locally without errors?  What is your Golem app package name?

**Comment by aeynaud** [comment]
Using `devtools::check()`  shows me that there are no errors, I do have some warnings and a note but upon inspection, it should not matter too much (I think). I do not have a license specification, there is a non-standard directory named 'database' found at top level. There are also a few warnings regarding "no visible binding for global variable 'example' ". 

Launching the app with golem works flawlessly on all my machines even if there are some of there warnings - no errors. 

Does the polished app name need to be exactly the same as the golem package name being created?

**Comment by aeynaud** [comment]
Hello, I am still having trouble deploying to polished with my Golem app. Given that my issue could be too complex to troubleshoot in this thread, I am wondering if there are any guides/regarding polished deployment? The one given on your website is clear and concise, however it does not contain much information on potential issues/requirements. 

For example, if both the golem app and the polished app reference both **need** to have the same name for successful deployment - there is no way for me to know about it. Thank you in advance for your help!

**Comment by aeynaud** [comment]
Update: Still not working. 

So I deleted and re-installed all my package dependencies. I realized that I could not deploy even a simple base shiny app to polished hosting, but that was solved by downloading the _dockerfiler_ package. I hope that this had fixed my problem, but it did not. So, simple shiny apps get deployed, but not my golem app. 

However, the warnings are now different when attempting to deploy my golem app. 
![image](https://user-images.githubusercontent.com/52440398/181872298-e9ad443a-c690-4355-8622-e8c769f23b1f.png)

When looking at the logs, here is what I see:
![image](https://user-images.githubusercontent.com/52440398/181872349-d256d8a5-6d12-4e77-ad08-7611e84ae40e.png)

I tried everything to fix these individual issues, re-building the NAMESPACE and DESCRIPTION of my golem app, updating all dependencies, investigating why devtools may be returning this issue etc.. but I am stuck. 

Could anyone please help me regarding the above?

**Comment by merlinoa** [comment]
It looks like your app is now running on polished hosting.  Was your issue resolved?  If so, can you please let us know how you resolved your issue.  Thanks.

**Comment by aeynaud** [comment]
Hi, yes it finally worked when I set the deployment RAM to 8GB. My app only uses a fraction of that however, but it is all god now. Thank you.
