### ISSUE TITLE
How to use polished without polished.tech

### ISSUE THREAD

**Issue by dmenne** [Tychobra/polished#194]
From reading the readme, one can get the impression that polished can be used standalone without using polished.tech, i.e. as an alternative to shinymanager.

Looking more carefully, I got the impression that this is not possible. If this assumption is not correct, is there an example?

Relying on a provider using proprietary code is not an option for our company.

**Comment by merlinoa** [comment]
Polished cannot be used without polished.tech/the polished API backend.  

We hope to open source the backend at some point so that people can run it on their own servers, but that is not on our immediate todo list.
