### ISSUE TITLE
Super sad seeing polished being shut down

### ISSUE THREAD

**Issue by fegue** [Tychobra/polished#224]
This was a great service and I think you did a tremendous job!

Any chance to fork your backend? ;)

**Comment by cwilligv** [comment]
I second that, it was a great package. sad to see it go down just like that.

**Comment by durraniu** [comment]
Was there an announcement somewhere of polished being shutdown? I don't see that on github or website.

**Comment by fegue** [comment]
@durraniu I got an Email announcing that Polished would be shutdown but that they would keep up the authentication service for now. The same day, the website was down, and I wasn't able to reach the dashboard. 
But now everything seems to be back to normal. Nothing on the website as well. I have only used Polished for authentication, though. I don't know how the hosting service is affected.
@merlinoa Some clarification would be great. I would like to know if I can still rely on the service. Uncertainty definitely kills the business. And I would be happy to pay for the authentication service as well. Because it is good!

**Comment by durraniu** [comment]
@fegue Thanks for responding to my question. I hope they provide clarification soon.

**Comment by merlinoa** [comment]
Sorry for my slow response.  I have been extremely busy which is one reason I decided to shut down polished hosting.  For clarification, only the hosting is being shut down.  The hosting was just too time consuming and expensive to operate.  The auth will continue to operate indefinitely.  I have no plans to shut it down.

I hope to open source the hosting portion of polished as soon as I can find some time to put it together.

**Comment by HugoGit39** [comment]
Too bad indeed! Worked great

**Comment by fegue** [comment]
Thank you so much for keeping up the auth! 
Great service!
