### ISSUE TITLE
Firebase function to optionally send email when user invited

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished#23]

**Comment by phoward38** [comment]
@merlinoa Is this still relevant w/ our current Welcome Email functionality?

**Comment by phoward38** [comment]
- [ ] Create function in API plumber to send email
- [ ] Create module for new tab in Admin Panel where user can customize template & see preview
  - [ ] Add option to send email after invite
    - @merlinoa Part of `global_sessions_config` or input in Admin Panel?

**Comment by merlinoa** [comment]
This has been implemented
