### ISSUE TITLE
Just an opinion on the package with some questions

### ISSUE THREAD

**Issue by MislavSag** [Tychobra/polished#39]
Just want to give my opinion on the package. I tried it today but can't get it work. can't even guess what is wrong. There are too many questions:
1. Why we have to change all structure of our app only for authentication? For example, golem package has it's own recommended structure, so I had to change they recommended structure only to include this authentication. 
2. Is project name a shiny project, R project or just a folder with that name?
3. How exactly to add "apps/{your Shiny app name}/users/{your email address} document in Firebase?
4. What should I see if I run shiny app locally?
5. Is there some special configuration if I deploy app on shinyapps.io?
6. Do I have to "secure m shiny app", or should it work without it?
7. Do you have a live app where we can see how it is working?
...

For me, it is too complicated for now to implement this solution in my existing apps.

**Comment by merlinoa** [comment]
Hi MislavSag,

Thanks for attempting to get it working.  Yes I agree that the set up is too complicated at this point.  It is a work in progress.  I am currently working on moving away from Firestore which simplifies everything quite a bit.

In response to you questions:

1. You don't have to change the structure of your Shiny apps.  To use polished, you need to set up your Firebase project configuration (i.e. the "polished-<project name>" folder) and pass your Shiny `ui` and `server` to `polished::secure_ui()` and `polished::secure_server()`.  The structure proposed in the README is just our preferred "project" structure.
2. The "project" in this sense is just a folder
3. You can do that through the Firebase web UI at firebase.gooogle.com.  In the next release of polished we will no longer be using Firestore, so this step will no longer be needed.
4. A sign in screen
5. No
6. To secure the Shiny app you need to pass your Shiny `ui` and `server` to `polished::secure_ui()` and `polished::secure_server()`.
7. There are some apps in the "inst/examples/" directory of the package.  You need to set the values in the "config.yml" of these apps to run them.  I would recommend holding off on running these, or using polished in general, until the next release of polished which should be later this week or over the weekend.

Thanks again for trying the package out, and thanks for the feedback.  I am aiming to significantly reduce the complexity of the setup process in the next release.
