### ISSUE TITLE
How to use polished on local server? 

### ISSUE THREAD

**Issue by pkosmos** [Tychobra/polished#46]
Hi! There is no instruction how I can install polished on my local Shiny Server
There is instruction only for cloud - firebase

**Comment by merlinoa** [comment]
@pkosmos Thanks for the issue.

polished currently requires Firebase for authentication.  You can't use your own authentication system.  An option to use Postgres for authentication is in development.  We hope to have it available in the next couple of weeks.

We are also working on improving the documentation.  Thanks for your interest in polished!
