### ISSUE TITLE
Is it global_sessions_config or app_config or firebase_config in secure_ui function?

### ISSUE THREAD

**Issue by howaskew** [Tychobra/polished#49]
> Additionally you need to pass the firebase functions url and the app name to global_sessions_config() in your "global.R" file.
> 
> You can find a full working example in the "inst/examples/" directory in this package.

I couldn't find the examples mentioned, as already raised in issue #48 , but working through the files I could find, I got as far as successfully reading in the config.yml and trying to secure the UI.

From ?secure_ui:

> secure_ui(
>   ui,
>   firebase_config,
>   sign_in_page_ui = NULL,
>   custom_admin_ui = NULL,
>   custom_admin_button_ui = admin_button_ui("polished")
> )
> Arguments
> ui	UI of the application.
> firebase_config Firebase configuration.

I couldn't find firebase_config and .global_session doesn't appear to work so I tried app_config instead of firebase_config, assuming the function required the firebase_functions_url, app_name and maybe the API key.

This got my app as far as opening with the login screen, accepting my email and asking for a password - but nothing happens when I press Sign In.

**Comment by merlinoa** [comment]
Hi @howaskey

Thanks for the issue, and thanks for trying out polished!  

You need to provide your own Firebase configuration from your Firebase project.  You can set up a Firebase project at firebase.google.com if you haven't set one up already.  You can then store your Firebase configuration in a "config.yml" file, read in the configuration into your Shiny app, and pass it to `secure_ui()`.  You need to pass your Firebase functions url along with your PostgreSQL database connection to `global_sessions_config()`.

The most basic example Shiny app using polished is available in "inst/examples/polished_example_01".  I just added an additional example with a custom sign in page in "inst/examples/custom_sign_in".

I know the documentation is lacking right now, and the set up is not very straight forward.  We are working on it, and we plan to provide more complete examples + videos as soon as we have the time.

**Comment by howaskew** [comment]
Thanks - package looking good! I had my firebase set up ok. I found what I was looking for in the custom sign in example...

> secure_ui(
  ui,
  firebase_config = app_config$firebase,
  sign_in_page_ui = source("custom_sign_in.R", local = TRUE)$value
)

This makes sense now.
