### ISSUE TITLE
Login without invite required? 

### ISSUE THREAD

**Issue by diegollarrull** [Tychobra/polished#51]
Hi, 

I would like to implement a login system but I couldn't find any way for users to log in without an invite sent to them. I would like to avoid using invites as I am not able to know in advance who can log in. Is this feature possible? 

Best regards,

**Comment by merlinoa** [comment]
Hi @diegollarrull 

Thanks for the issue.  

It is currently not possible to sign in + register without an invite, but something we plan to add.  I just opened #52 to make a note of it. Hopefully we can get around to it in the next few weeks.  I will keep this issue open until the feature is implemented.

**Comment by diegollarrull** [comment]
Thank you!

**Comment by merlinoa** [comment]
@diegollarrull I finally got around to putting together an initial implementation of this functionality.  There is a minimal demo app linked from the README https://github.com/Tychobra/polished/blob/master/README.md#2-do-not-require-invite-for-sign-in--register.  If you are still interested, please install the latest version of `polished` from GitHub and give it a whirl!  I would be very grateful for any feedback.  I am closing this issue out now.  Please open new issues if you find any bugs!
