### ISSUE TITLE
no password reset email for auth

### ISSUE THREAD

**Issue by cawthm** [Tychobra/polished#53]
This is a potentially very useful package; thank you for making it.

I've followed the steps in the readme, using `polished_example_01` as my hello world app on a remote machine running shiny-server.  I can see the app's default login screen being served, but I can't get my admin email (same one as firebase project owner/ same one created on local machine with `polished::create_app_user()`) to work with the landing page login ui:

- if i attempt a forgot password step, I get the popup js saying a email w/a new password has been sent, but no email ever arrives (i've checked the spam; nada),

- alternatively, if I attempt to register de novo, I get an error (which I expect, having already initialized an admin user `polished::create_app_user()` step with my email): 

"Error: The email address is already in use by another account."

Any advice?

More generally, it would be very helpful to better understand the flow of account adding/ password set up/ firebase/ the user db.

Thank you again for this work in progress.

**Comment by cawthm** [comment]
i started from scratch and re-installed everything.  I'm now getting a slightly different behavior, but I have one very simple Q:  _How does one initially invite users_?

It seems `create_app_user` is a purely db function; ie it doesn't update firebase in any way.

Thank  you.

**Comment by merlinoa** [comment]
Hi @cawthm.  Thanks so much for trying out `polished`.  

We still have some work to do on documenting and streamlining the initial setup.  Sorry for any struggles you had to endure in the initial setup.  

Once you have polished setup, you invite the first user with the `create_app_user()` function.  I usually run this function to invite myself to register for the app as an app admin (`polished` currently requires users to be invited to the app in order to sign in or register.  Once invite, app admins can invite other users to the app using the `polished` admin dashboard).  Once you sign in as an admin you can access the polished admin dashboard to invite additional users.

You are right the `create_app_user()` is purely a db function.  In `polished` all user authorization information is stored in the database.  We only use Firebase for authentication and a couple Firebase functions.

Here is a link to the video for additional context: https://www.youtube.com/watch?v=g7I9Y2VQ-2Q

**Comment by cawthm** [comment]
Thank you for the reply.

So, in following the setup I too have added users via `create_app_user()`, starting with myself as an admin.  Should I expect to receive an email at that point?  Because I don't.  And given that `create_app_user()` only adds credentials to a postgres db (local, in my case) , by what mechanism would an invite be generated?

Incidentally, if I log into the local postgres db and inspect the tables in the polished schema, I see successfully-added emails and hashed credentials (eg, app_users, apps, etc).  Ie, that seems to be working correctly.

Also, if I go to the firebase console > authentication > users, I can add new users and/or change send them a password via reset password.  But this doesn't do anything: when I enter the created admin email on the polished login landing page, I simply see the following js popup "Not authorized: You must have an invite to access this app"

**Comment by merlinoa** [comment]
polished does not send out an email when you invite a user to your app either through the polished admin panel or using `create_app_user()`.  The only email that polished automatically sends is an email verification email after a new user registers for your app.

When you invite a new user to your app all polished does is add an entry to the database.  This entry authorizes the user to access your app.  The invited user can then register and sign in.  The registration and sign in process uses Firebase authentication.

Adding a user to the Firebase auth dashboard at "firebase console > authentication > users" does not invite the user to access your app.  It only registers the user for Firebase, but the user will still need to be invited via the polished admin panel or using `create_app_user()`.  This allows for each of your users to have 1 email/password and sign in to multiple Shiny apps using your polished project.

Sorry if this is unclear.

**Comment by cawthm** [comment]
Ok; I think I understand the auth flow, but i'm still having an issue.

One more troubleshooting stab, if you'll indulge me once more (and thank you for your kind patience):

1. To recap, I've followed the steps in the github readme page, including the successful creation of firebase project 'polished-my-project' and the creation of users via `create-app_user()`, granting admin access for `demo_app` to _my_email@gmail.com_ as admin.

2. I'm running shiny-server on a machine with the following resultant directory structure:
../home/my-project/   
...............|__polished-my-project/
....................|__functions/  
....................|__firebase.json  
...............|__demo_app/  
....................|__app.R

In `shiny-server.conf`, the server is pointed at the project directory, eg:
`site_dir /home/my-project;`

When I navigate to the resource, shiny-server shows a landing page with 
**Index of /**
    [demo_app/](url)
    [polished-my-project](url)

If I navigate to demo_app, I see the Sign In screen, click 'Not a member? Register!', and then attempt to register _my_email@gmail.com_, but get this canned error:
![image](https://user-images.githubusercontent.com/1149250/74595284-53404180-5005-11ea-8d46-64b1bed64fe1.png)

I realize I'm adding shiny-server to the question mix here, but this is surely anticipated by polished itself.

Do you have any troubleshooting advice for what I'm doing wrong?

**Comment by merlinoa** [comment]
Yes `polished` works with shiny-server, so we should be able to get this working. 

When you attempt to register, `polished` checks if you are authorized to access the app in the  "polished.app_users" table.  If you have an entry in this table giving you access to the "demo_app" then you should be able to register.  I would probably start troubleshooting by inspecting the "polished.app_users" table.  If there is not a row with your "user_uid" and the "app_name" of "demo_app", then there was an issue with the invite created by `create_app_user()`.  If there is an entry for you in this table, then there is some other configuration issue.

Sorry about the lack of documentation; polished is still a work in progress.  I would be happy to do a quick screen share and see if we can fix it, or if it would be possible for you to give me temporary access to the database and code I will look into it.

**Comment by cawthm** [comment]
i've reached out to you with some addl details at your listed contact email-
