### ISSUE TITLE
Sign-out button

### ISSUE THREAD

**Issue by cbouffard** [Tychobra/polished#55]
Hi,

The sign-out button is not working in the demo app. 

And is there a way to add a sign out button for non admin users?

Thanks

**Comment by cbouffard** [comment]
Ok it's working now with the command:

sign_out_from_shiny(session = session,user=session$userData$user())

**Comment by merlinoa** [comment]
yes sorry I didn't get back sooner.  You do not need to set the second argument (i.e. the `user` argument).  That argument will soon be removed from `sing_out_from_shiny()`.
