### ISSUE TITLE
add our apps dashboard as an example app in "inst/examples/apps_dashboard"

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished#57]
Please make a new branch for this.  

Do __not__ use our normal "shiny_app" directory setup; just put the file/folders for the `apps_dashboard` app directly in the "inst/examples/apps_dashboard/" folder.  Set up the apps dashboard to show the 2 existing example apps in the apps dashboard.  Use our internal apps dashboard with the cool sign in page background.

**Comment by phoward38** [comment]
- [ ] Use [Basic Claims Analytics](https://github.com/Tychobra/shiny-insurance-examples/tree/master/basic-insurer-dashboard) app from Tychobra example apps
  - [ ] Use [Apexcharter](https://github.com/dreamRs/apexcharter) instead of `highcharter`
  - [ ] Remove other 2 tabs (only keep Dashboard)
  - [ ] Change `Severity` to mean (or something simpler)

**Comment by merlinoa** [comment]
@phoward38 let's also keep versions of each of the minimal apps.  The minimal apps are good for our testing during development, and they are easier for developers implementing polished to reference how polished works without having wade through a bunch of random demo app logic.

So, for each of the new demo apps, let's please keep a copy of the minimal version.  The minimal and non-minimal apps will need different names in their "config.yml".  Let me know if you have questions and we can talk through it.

**Comment by phoward38** [comment]
The new demo apps are ready. The only one that I couldn't replicate exactly is the bottom time-series chart on the 'Interest Rate Walk' app.

@merlinoa Where do you want me to place the new (non-minimal) example app directories (instead of in `inst/examples/`)?

**Comment by phoward38** [comment]
Created PR #61

**Comment by phoward38** [comment]
Created [repo](https://github.com/Tychobra/polished_example_apps) for non-minimal example apps & apps dashboard

**Comment by merlinoa** [comment]
Awesome thanks!
