### ISSUE TITLE
Add new Logo to Admin Panel

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polished#62]
- [x] Add the new logo (same size/dims as `polished_hosted`) to Admin Panel of polished

**Comment by phoward38** [comment]
Added w/ ddb862648bd6b1df693a063015bf05dfa0c5d268

**Comment by phoward38** [comment]
@merlinoa Let me know when you have time next week to go over how to test changes to a package like this

**Comment by merlinoa** [comment]
I made some fixes here: c2e12f4a67395b13e18016e0b1ddbd9b783ea2da. Yea let's go over the process next week.
