### ISSUE TITLE
Sign Out Button

### ISSUE THREAD

**Issue by cerees** [Tychobra/polished#64]
I'm not sure how the sign out process works for non-admins.  I see a function sign_out_from_shiny, but I'm struggling to find documentation on how to put a signout button where the admin panel button would normally be located.

**Comment by merlinoa** [comment]
To create a custom sign out button, you need to call `polished::sign_out_from_shiny(session)` followed by `session$reload()`.

Here is an example: https://github.com/Tychobra/polished/blob/65af233738ee6fe52079c395b47b9deb8b98ae75/inst/examples/polished_example_01/server.R#L8

I just added the above sign out button to the example Shiny app deployed here https://tychobra.shinyapps.io/polished_example_01 if you want to test it out live.

**Comment by cerees** [comment]
Perfect thanks I'll check it out.

**Comment by merlinoa** [comment]
@cerees I am going to close out this issue.  Please reopen if anything in my above comment is unclear.  Thanks!
