### ISSUE TITLE
secure_ui.R:149 - verify_email_module_ui call missing required firebase_config argument

### ISSUE THREAD

**Issue by timshac** [Tychobra/polished#65]
I think this happened after you moved firebase_config to Sessions object.

Thanks for this great R package!

-Tim

**Comment by merlinoa** [comment]
Thanks @timshac !  Yes you are correct that this bug was introduced when I moved the firebase config to the `Sessions`.  Nice call!

It should be fixed with: 6afbd7719f88916b5cbd9ab18f8be986a9ee69d9

Please reopen if that did not resolve your issue.  Thanks!
