### ISSUE TITLE
Fix "Unique Daily Users" chart x-axis labels

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished#66]
![Screen Shot 2020-04-02 at 12 37 13 PM](https://user-images.githubusercontent.com/4030554/78683178-f9e5e780-78bc-11ea-998b-0ffc149231e4.png)

**Comment by phoward38** [comment]
- Create branch for Polished updates
- Testing:
  - Use devtools' `loadall` then test w/ example app
  - Use devtools' `document` when adding new documentation
  - Use devtools' `check`

TO DO:
- [ ] Replace `Authenticating` screen w/ loading button

**Comment by phoward38** [comment]
Created PR #70 for fix

**Comment by merlinoa** [comment]
merged thanks!
