### ISSUE TITLE
Value Boxes show 'NaN'

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polished#78]
When adding Polished to `CSIA_UP`, the value boxes in the Admin Panel display `NaN`. Just wanted to confirm that you want this to display instead of `0` or showing no value

**Comment by phoward38** [comment]
Fixed w/ 0038194cf5bd657960e7c986625738cf9c42dda6

**Comment by phoward38** [comment]
@phoward38 Need to test

**Comment by merlinoa** [comment]
@phoward38 any update on this?

**Comment by phoward38** [comment]
Fixed w/ 477d5c1ecf56ac03fc71c1b071f6cc6ccb25f84e
