### ISSUE TITLE
Admin Panel sidebar toggle + table bug

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polished#79]
Ex: Happened in `CSIA_UP` deployed app after installing newest polished
- Table border lags when toggling the sidebar. Fixed this in `polished_hosted` by removing scrollX
  - [ ] Confirm this doesn't mess up table when changing window size

**Comment by merlinoa** [comment]
We don't want to remove scrollX.  It messes up the tables on mobile.  Please change this back.  Look at dashboard.polished.tech for example on your phone.

**Comment by phoward38** [comment]
Fixed w/ db7f36a4125d16141f5ab6887c5db54e9efe161e
- Added JS callback in DT to add `table-responsive` class
- Also added to `Polished Hosted` (f56f7b5c9a613143d76c410881443fadec55899e)
