### ISSUE TITLE
UI updates from Polished Hosted

### ISSUE THREAD

**Issue by phoward38** [Tychobra/polished#80]
Apply UI updates done in `polished_hosted`:
- [x] `shinyDashboardPlus`
- [x] @phoward38 Look up others

Before committing:
- [x] (**IMPORTANT**) Run `devtools::check()` (since you're bringing in `shinyDashboardPlus`)

**Comment by phoward38** [comment]
@phoward38 Confirm all of these are done (including admin updates) & close

**Comment by phoward38** [comment]
@merlinoa Do we want to make the `Dashboard` chart interactive (like in `polished_hosted`)?

**Comment by merlinoa** [comment]
@phoward38 no let's not update the dashboard chart for now.  I'm still not sure if we are going to keep that dashboard long term.  Closing this out.
