### ISSUE TITLE
Azure Authentication Support

### ISSUE THREAD

**Issue by benkates** [Tychobra/polished#82]
I see Firebase as a solution but figured I'd throw my hat in the ring for Azure Authentication. Nice to see this project develop into the state it's in.

**Comment by merlinoa** [comment]
Thanks @benkates,

Adding support for Azure authentication is not on our short list of todos at the moment, but we  hope to provide support at some point.  It will be at least a couple months before it is implemented.  I'll keep this issue open and if there is a lot of interest in adding Azure Authentication support we can bump it up in our priority list.  Thanks for your interest in polished!

**Comment by merlinoa** [comment]
Azure Authentication is now supported by the most recent version of polished on GitHub.  To enable Azure/Microsoft.com sign in, pass "microsoft" to the `sign_in_providers` argument of `global_sessions_config()` in your global.R script and follow the instructions for configuring Firebase to support Microsoft sign in here: https://polished.tech/docs/firebase-setup

Please send me an email if anything in the instructions is unclear.  Thanks!
