### ISSUE TITLE
User Role

### ISSUE THREAD

**Issue by BernoGreyling** [Tychobra/polished#84]
Hi, Thanks for the great package!

I see you guys removed the user role field? Is it coming back at some stage or has it completely been removed?

**Comment by merlinoa** [comment]
Thanks @BernoGreyling!

Yes will eventually to reimplement user "roles", but it is not currently on our short list of updated to polished.  I will keep this issue open until we reimplement the user roles.

**Comment by phoward38** [comment]
Hi @BernoGreyling,

The `User Roles` feature is back! Closing this issue.

**Comment by bernorev** [comment]
@phoward38 Awesome thanks!
