### ISSUE TITLE
Bad with shinycumtumloader

### ISSUE THREAD

**Issue by jinseob2kim** [Tychobra/polished#88]
Thanks for great package.

I use loading image with [shincustomloader](https://github.com/emitanaka/shinycustomloader)  package, but the image looks bad after applying polished 

![Screenshot from 2020-06-12 06-44-57](https://user-images.githubusercontent.com/33089958/84442277-43b1cc00-ac78-11ea-823a-7f9584b34de6.png)

Sincerely
Jinseob Kim

**Comment by merlinoa** [comment]
Thanks @jinseob2kim .  Could you please provide a minimal reproducible example?  If so, I'd be happy to look into it.

**Comment by jinseob2kim** [comment]
This is example

```r
library(shiny)

ui <- polished::secure_ui(
    fluidPage(
        fluidRow(
            column(
                6,
                h1("Hello Shiny!")
            ),
            column(
                6,
                br(),
                actionButton(
                    "sign_out",
                    "Sign Out",
                    icon = icon("sign-out-alt"),
                    class = "pull-right"
                )
            ),
            column(
                12,
                **shinycustomloader::withLoader(verbatimTextOutput("user_out"), loader = "loader6")**
            )
        )
    )
)

server <- polished::secure_server(function(input, output, session) {
    output$user_out <- renderPrint({
        session$userData$user()
    })
    
    observeEvent(input$sign_out, {
        sign_out_from_shiny(session)
        session$reload()
    })
})



shinyApp(ui, server, onStart = function() {
    library(polished)
    
    # configure the global sessions when the app initially starts up.
    polished::global_sessions_config(
        app_name = "my_first_shiny_app",
        api_key = "<your polished.tech secret API key>"
    )
})
```

**Comment by phoward38** [comment]
Hi Jinseob,

I ran the example app you provided with & without using `polished`, but I'm not seeing any differences in the `shinycustomloader::withLoader()` loading object. Can you provide a screenshot of the loader in the provided example with & without polished?

**Comment by jinseob2kim** [comment]
Today, I can't reproduce the above figure. It' seems to be ok. 
I will comment when I see the same problem. Thanks for your feedback.
Sincerely
