### ISSUE TITLE
uppercase letters in user emails

### ISSUE THREAD

**Issue by tbrown122387** [Tychobra/polished#89]
I just added a friend as a user to my shiny app. His email featured a single, leading uppercase letter. Unfortunately, every time he clicked "First time user? Register here!”, it complained that he wasn't registered. 

In the dashboard I deleted his email, and re-added it, changing the uppercase letter to a lowercase letter, and it worked.

**Comment by merlinoa** [comment]
Thanks @tbrown122387 .  All emails are now converted to lowercase in the polished.tech dashboard before they are saved.  This is consistent with how polished (and I believe most other authentication services) handle email addresses.  I am going to close out this issue.  Please reopen if that did not resolve this issue.
